[project]
name = "sunshine-mcp"
version = "0.1.0"
description = "Find locations with good weather/sunshine within a reasonable distance"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx",
    "click",
]
